// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: asset.proto

package assetpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Count struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         map[string]int32       `protobuf:"bytes,1,rep,name=count,proto3" json:"count,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Count) Reset() {
	*x = Count{}
	mi := &file_asset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Count) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Count) ProtoMessage() {}

func (x *Count) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Count.ProtoReflect.Descriptor instead.
func (*Count) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{0}
}

func (x *Count) GetCount() map[string]int32 {
	if x != nil {
		return x.Count
	}
	return nil
}

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	ParentID      int64                  `protobuf:"varint,3,opt,name=ParentID,proto3" json:"ParentID,omitempty"`
	ObjectName    string                 `protobuf:"bytes,4,opt,name=ObjectName,proto3" json:"ObjectName,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=Size,proto3" json:"Size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_asset_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{1}
}

func (x *File) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *File) GetParentID() int64 {
	if x != nil {
		return x.ParentID
	}
	return 0
}

func (x *File) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

func (x *File) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type Files struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*File                `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Files) Reset() {
	*x = Files{}
	mi := &file_asset_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Files) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Files) ProtoMessage() {}

func (x *Files) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Files.ProtoReflect.Descriptor instead.
func (*Files) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{2}
}

func (x *Files) GetData() []*File {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_asset_proto protoreflect.FileDescriptor

const file_asset_proto_rawDesc = "" +
	"\n" +
	"\vasset.proto\x12\x05asset\x1a\x1bgoogle/protobuf/empty.proto\"p\n" +
	"\x05Count\x12-\n" +
	"\x05count\x18\x01 \x03(\v2\x17.asset.Count.CountEntryR\x05count\x1a8\n" +
	"\n" +
	"CountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"z\n" +
	"\x04File\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1a\n" +
	"\bParentID\x18\x03 \x01(\x03R\bParentID\x12\x1e\n" +
	"\n" +
	"ObjectName\x18\x04 \x01(\tR\n" +
	"ObjectName\x12\x12\n" +
	"\x04Size\x18\x05 \x01(\x03R\x04Size\"(\n" +
	"\x05Files\x12\x1f\n" +
	"\x04data\x18\x01 \x03(\v2\v.asset.FileR\x04data2\xb0\x01\n" +
	"\fAssetService\x122\n" +
	"\bGetCount\x12\x16.google.protobuf.Empty\x1a\f.asset.Count\"\x00\x125\n" +
	"\vGetRecently\x12\x16.google.protobuf.Empty\x1a\f.asset.Files\"\x00\x125\n" +
	"\vGetFavorite\x12\x16.google.protobuf.Empty\x1a\f.asset.Files\"\x002A\n" +
	"\vFileService\x122\n" +
	"\tWriteDone\x12\v.asset.File\x1a\x16.google.protobuf.Empty\"\x00B\x13Z\x11api/asset;assetpbb\x06proto3"

var (
	file_asset_proto_rawDescOnce sync.Once
	file_asset_proto_rawDescData []byte
)

func file_asset_proto_rawDescGZIP() []byte {
	file_asset_proto_rawDescOnce.Do(func() {
		file_asset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_asset_proto_rawDesc), len(file_asset_proto_rawDesc)))
	})
	return file_asset_proto_rawDescData
}

var file_asset_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_asset_proto_goTypes = []any{
	(*Count)(nil),         // 0: asset.Count
	(*File)(nil),          // 1: asset.File
	(*Files)(nil),         // 2: asset.Files
	nil,                   // 3: asset.Count.CountEntry
	(*emptypb.Empty)(nil), // 4: google.protobuf.Empty
}
var file_asset_proto_depIdxs = []int32{
	3, // 0: asset.Count.count:type_name -> asset.Count.CountEntry
	1, // 1: asset.Files.data:type_name -> asset.File
	4, // 2: asset.AssetService.GetCount:input_type -> google.protobuf.Empty
	4, // 3: asset.AssetService.GetRecently:input_type -> google.protobuf.Empty
	4, // 4: asset.AssetService.GetFavorite:input_type -> google.protobuf.Empty
	1, // 5: asset.FileService.WriteDone:input_type -> asset.File
	0, // 6: asset.AssetService.GetCount:output_type -> asset.Count
	2, // 7: asset.AssetService.GetRecently:output_type -> asset.Files
	2, // 8: asset.AssetService.GetFavorite:output_type -> asset.Files
	4, // 9: asset.FileService.WriteDone:output_type -> google.protobuf.Empty
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_asset_proto_init() }
func file_asset_proto_init() {
	if File_asset_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_asset_proto_rawDesc), len(file_asset_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_asset_proto_goTypes,
		DependencyIndexes: file_asset_proto_depIdxs,
		MessageInfos:      file_asset_proto_msgTypes,
	}.Build()
	File_asset_proto = out.File
	file_asset_proto_goTypes = nil
	file_asset_proto_depIdxs = nil
}
