// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: asset.proto

package assetpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Count struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         map[string]int32       `protobuf:"bytes,1,rep,name=count,proto3" json:"count,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Count) Reset() {
	*x = Count{}
	mi := &file_asset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Count) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Count) ProtoMessage() {}

func (x *Count) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Count.ProtoReflect.Descriptor instead.
func (*Count) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{0}
}

func (x *Count) GetCount() map[string]int32 {
	if x != nil {
		return x.Count
	}
	return nil
}

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	ParentID      *int64                 `protobuf:"varint,3,opt,name=ParentID,proto3,oneof" json:"ParentID,omitempty"`
	ObjectName    string                 `protobuf:"bytes,4,opt,name=ObjectName,proto3" json:"ObjectName,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=Size,proto3" json:"Size,omitempty"`
	FullName      *string                `protobuf:"bytes,6,opt,name=FullName,proto3,oneof" json:"FullName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_asset_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{1}
}

func (x *Resource) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetParentID() int64 {
	if x != nil && x.ParentID != nil {
		return *x.ParentID
	}
	return 0
}

func (x *Resource) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

func (x *Resource) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Resource) GetFullName() string {
	if x != nil && x.FullName != nil {
		return *x.FullName
	}
	return ""
}

type ResourcePrimaryID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourcePrimaryID) Reset() {
	*x = ResourcePrimaryID{}
	mi := &file_asset_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourcePrimaryID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourcePrimaryID) ProtoMessage() {}

func (x *ResourcePrimaryID) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourcePrimaryID.ProtoReflect.Descriptor instead.
func (*ResourcePrimaryID) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{2}
}

func (x *ResourcePrimaryID) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type Resources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Resource            `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resources) Reset() {
	*x = Resources{}
	mi := &file_asset_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resources) ProtoMessage() {}

func (x *Resources) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resources.ProtoReflect.Descriptor instead.
func (*Resources) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{3}
}

func (x *Resources) GetData() []*Resource {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_asset_proto protoreflect.FileDescriptor

const file_asset_proto_rawDesc = "" +
	"\n" +
	"\vasset.proto\x12\x05asset\x1a\x1bgoogle/protobuf/empty.proto\"p\n" +
	"\x05Count\x12-\n" +
	"\x05count\x18\x01 \x03(\v2\x17.asset.Count.CountEntryR\x05count\x1a8\n" +
	"\n" +
	"CountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xbe\x01\n" +
	"\bResource\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1f\n" +
	"\bParentID\x18\x03 \x01(\x03H\x00R\bParentID\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"ObjectName\x18\x04 \x01(\tR\n" +
	"ObjectName\x12\x12\n" +
	"\x04Size\x18\x05 \x01(\x03R\x04Size\x12\x1f\n" +
	"\bFullName\x18\x06 \x01(\tH\x01R\bFullName\x88\x01\x01B\v\n" +
	"\t_ParentIDB\v\n" +
	"\t_FullName\"#\n" +
	"\x11ResourcePrimaryID\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"0\n" +
	"\tResources\x12#\n" +
	"\x04data\x18\x01 \x03(\v2\x0f.asset.ResourceR\x04data2\xb8\x01\n" +
	"\fAssetService\x122\n" +
	"\bGetCount\x12\x16.google.protobuf.Empty\x1a\f.asset.Count\"\x00\x129\n" +
	"\vGetRecently\x12\x16.google.protobuf.Empty\x1a\x10.asset.Resources\"\x00\x129\n" +
	"\vGetFavorite\x12\x16.google.protobuf.Empty\x1a\x10.asset.Resources\"\x002\x89\x01\n" +
	"\x0fResourceService\x126\n" +
	"\tWriteDone\x12\x0f.asset.Resource\x1a\x16.google.protobuf.Empty\"\x00\x12>\n" +
	"\x0fGetResourceInfo\x12\x18.asset.ResourcePrimaryID\x1a\x0f.asset.Resource\"\x00B\x13Z\x11api/asset;assetpbb\x06proto3"

var (
	file_asset_proto_rawDescOnce sync.Once
	file_asset_proto_rawDescData []byte
)

func file_asset_proto_rawDescGZIP() []byte {
	file_asset_proto_rawDescOnce.Do(func() {
		file_asset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_asset_proto_rawDesc), len(file_asset_proto_rawDesc)))
	})
	return file_asset_proto_rawDescData
}

var file_asset_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_asset_proto_goTypes = []any{
	(*Count)(nil),             // 0: asset.Count
	(*Resource)(nil),          // 1: asset.Resource
	(*ResourcePrimaryID)(nil), // 2: asset.ResourcePrimaryID
	(*Resources)(nil),         // 3: asset.Resources
	nil,                       // 4: asset.Count.CountEntry
	(*emptypb.Empty)(nil),     // 5: google.protobuf.Empty
}
var file_asset_proto_depIdxs = []int32{
	4, // 0: asset.Count.count:type_name -> asset.Count.CountEntry
	1, // 1: asset.Resources.data:type_name -> asset.Resource
	5, // 2: asset.AssetService.GetCount:input_type -> google.protobuf.Empty
	5, // 3: asset.AssetService.GetRecently:input_type -> google.protobuf.Empty
	5, // 4: asset.AssetService.GetFavorite:input_type -> google.protobuf.Empty
	1, // 5: asset.ResourceService.WriteDone:input_type -> asset.Resource
	2, // 6: asset.ResourceService.GetResourceInfo:input_type -> asset.ResourcePrimaryID
	0, // 7: asset.AssetService.GetCount:output_type -> asset.Count
	3, // 8: asset.AssetService.GetRecently:output_type -> asset.Resources
	3, // 9: asset.AssetService.GetFavorite:output_type -> asset.Resources
	5, // 10: asset.ResourceService.WriteDone:output_type -> google.protobuf.Empty
	1, // 11: asset.ResourceService.GetResourceInfo:output_type -> asset.Resource
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_asset_proto_init() }
func file_asset_proto_init() {
	if File_asset_proto != nil {
		return
	}
	file_asset_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_asset_proto_rawDesc), len(file_asset_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_asset_proto_goTypes,
		DependencyIndexes: file_asset_proto_depIdxs,
		MessageInfos:      file_asset_proto_msgTypes,
	}.Build()
	File_asset_proto = out.File
	file_asset_proto_goTypes = nil
	file_asset_proto_depIdxs = nil
}
