syntax = "proto3";

package asset;

import "google/protobuf/empty.proto";

option go_package = "api/asset;assetpb";

service AssetService {
  rpc GetCount (google.protobuf.Empty) returns (Count) {};
  rpc GetRecently (google.protobuf.Empty) returns (Files) {};
  rpc GetFavorite (google.protobuf.Empty) returns (Files) {};
}

service FileService {
  rpc WriteDone (asset.File) returns (google.protobuf.Empty) {};
}

message Count {
  map<string, int32> count = 1;
}

message File {
  string ID         = 1;
  string Name       = 2;
  int64  ParentID   = 3;
  string ObjectName = 4;
  int64  Size       = 5;
}

message Files {
  repeated File data = 1;
}
