// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: explorer.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Count struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         map[string]int32       `protobuf:"bytes,1,rep,name=count,proto3" json:"count,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Count) Reset() {
	*x = Count{}
	mi := &file_explorer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Count) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Count) ProtoMessage() {}

func (x *Count) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Count.ProtoReflect.Descriptor instead.
func (*Count) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{0}
}

func (x *Count) GetCount() map[string]int32 {
	if x != nil {
		return x.Count
	}
	return nil
}

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=fullName,proto3" json:"fullName,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Count         int64                  `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_explorer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{1}
}

func (x *Resource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Resource) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Resource) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Resource) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Resource) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Resources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Resource            `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resources) Reset() {
	*x = Resources{}
	mi := &file_explorer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resources) ProtoMessage() {}

func (x *Resources) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resources.ProtoReflect.Descriptor instead.
func (*Resources) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{2}
}

func (x *Resources) GetData() []*Resource {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_explorer_proto protoreflect.FileDescriptor

const file_explorer_proto_rawDesc = "" +
	"\n" +
	"\x0eexplorer.proto\x12\bexplorer\x1a\x1bgoogle/protobuf/empty.proto\"s\n" +
	"\x05Count\x120\n" +
	"\x05count\x18\x01 \x03(\v2\x1a.explorer.Count.CountEntryR\x05count\x1a8\n" +
	"\n" +
	"CountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"t\n" +
	"\bResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bfullName\x18\x02 \x01(\tR\bfullName\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x03R\x05count\"3\n" +
	"\tResources\x12&\n" +
	"\x04data\x18\x01 \x03(\v2\x12.explorer.ResourceR\x04data2\xc4\x01\n" +
	"\x0fExplorerService\x125\n" +
	"\bGetCount\x12\x16.google.protobuf.Empty\x1a\x0f.explorer.Count\"\x00\x12<\n" +
	"\vGetRecently\x12\x16.google.protobuf.Empty\x1a\x13.explorer.Resources\"\x00\x12<\n" +
	"\vGetFavorite\x12\x16.google.protobuf.Empty\x1a\x13.explorer.Resources\"\x00B\x15Z\x13api/explorer;authpbb\x06proto3"

var (
	file_explorer_proto_rawDescOnce sync.Once
	file_explorer_proto_rawDescData []byte
)

func file_explorer_proto_rawDescGZIP() []byte {
	file_explorer_proto_rawDescOnce.Do(func() {
		file_explorer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_explorer_proto_rawDesc), len(file_explorer_proto_rawDesc)))
	})
	return file_explorer_proto_rawDescData
}

var file_explorer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_explorer_proto_goTypes = []any{
	(*Count)(nil),         // 0: explorer.Count
	(*Resource)(nil),      // 1: explorer.Resource
	(*Resources)(nil),     // 2: explorer.Resources
	nil,                   // 3: explorer.Count.CountEntry
	(*emptypb.Empty)(nil), // 4: google.protobuf.Empty
}
var file_explorer_proto_depIdxs = []int32{
	3, // 0: explorer.Count.count:type_name -> explorer.Count.CountEntry
	1, // 1: explorer.Resources.data:type_name -> explorer.Resource
	4, // 2: explorer.ExplorerService.GetCount:input_type -> google.protobuf.Empty
	4, // 3: explorer.ExplorerService.GetRecently:input_type -> google.protobuf.Empty
	4, // 4: explorer.ExplorerService.GetFavorite:input_type -> google.protobuf.Empty
	0, // 5: explorer.ExplorerService.GetCount:output_type -> explorer.Count
	2, // 6: explorer.ExplorerService.GetRecently:output_type -> explorer.Resources
	2, // 7: explorer.ExplorerService.GetFavorite:output_type -> explorer.Resources
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_explorer_proto_init() }
func file_explorer_proto_init() {
	if File_explorer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_explorer_proto_rawDesc), len(file_explorer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_explorer_proto_goTypes,
		DependencyIndexes: file_explorer_proto_depIdxs,
		MessageInfos:      file_explorer_proto_msgTypes,
	}.Build()
	File_explorer_proto = out.File
	file_explorer_proto_goTypes = nil
	file_explorer_proto_depIdxs = nil
}
