// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: explorer.proto

package authpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExplorerService_GetCount_FullMethodName    = "/explorer.ExplorerService/GetCount"
	ExplorerService_GetRecently_FullMethodName = "/explorer.ExplorerService/GetRecently"
	ExplorerService_GetFavorite_FullMethodName = "/explorer.ExplorerService/GetFavorite"
)

// ExplorerServiceClient is the client API for ExplorerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExplorerServiceClient interface {
	GetCount(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Count, error)
	GetRecently(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Resources, error)
	GetFavorite(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Resources, error)
}

type explorerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExplorerServiceClient(cc grpc.ClientConnInterface) ExplorerServiceClient {
	return &explorerServiceClient{cc}
}

func (c *explorerServiceClient) GetCount(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Count, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Count)
	err := c.cc.Invoke(ctx, ExplorerService_GetCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) GetRecently(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Resources, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Resources)
	err := c.cc.Invoke(ctx, ExplorerService_GetRecently_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) GetFavorite(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Resources, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Resources)
	err := c.cc.Invoke(ctx, ExplorerService_GetFavorite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExplorerServiceServer is the server API for ExplorerService service.
// All implementations must embed UnimplementedExplorerServiceServer
// for forward compatibility.
type ExplorerServiceServer interface {
	GetCount(context.Context, *emptypb.Empty) (*Count, error)
	GetRecently(context.Context, *emptypb.Empty) (*Resources, error)
	GetFavorite(context.Context, *emptypb.Empty) (*Resources, error)
	mustEmbedUnimplementedExplorerServiceServer()
}

// UnimplementedExplorerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExplorerServiceServer struct{}

func (UnimplementedExplorerServiceServer) GetCount(context.Context, *emptypb.Empty) (*Count, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCount not implemented")
}
func (UnimplementedExplorerServiceServer) GetRecently(context.Context, *emptypb.Empty) (*Resources, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecently not implemented")
}
func (UnimplementedExplorerServiceServer) GetFavorite(context.Context, *emptypb.Empty) (*Resources, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFavorite not implemented")
}
func (UnimplementedExplorerServiceServer) mustEmbedUnimplementedExplorerServiceServer() {}
func (UnimplementedExplorerServiceServer) testEmbeddedByValue()                         {}

// UnsafeExplorerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExplorerServiceServer will
// result in compilation errors.
type UnsafeExplorerServiceServer interface {
	mustEmbedUnimplementedExplorerServiceServer()
}

func RegisterExplorerServiceServer(s grpc.ServiceRegistrar, srv ExplorerServiceServer) {
	// If the following call panics, it indicates UnimplementedExplorerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExplorerService_ServiceDesc, srv)
}

func _ExplorerService_GetCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).GetCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_GetCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).GetCount(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_GetRecently_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).GetRecently(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_GetRecently_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).GetRecently(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_GetFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).GetFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_GetFavorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).GetFavorite(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ExplorerService_ServiceDesc is the grpc.ServiceDesc for ExplorerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExplorerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "explorer.ExplorerService",
	HandlerType: (*ExplorerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCount",
			Handler:    _ExplorerService_GetCount_Handler,
		},
		{
			MethodName: "GetRecently",
			Handler:    _ExplorerService_GetRecently_Handler,
		},
		{
			MethodName: "GetFavorite",
			Handler:    _ExplorerService_GetFavorite_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "explorer.proto",
}
